const text = ['Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor soluta minus quaerat ex voluptatem quidem dignissimos corporis delectus enim nemo nam architecto velit doloribus molestiae autem, rem optio libero excepturi unde commodi eaque nisi dolorum! Deserunt quia accusantium ipsa, labore nisi rem dolorum inventore illum aut deleniti quis ab voluptatum sit cupiditate modi. Nemo laboriosam maxime libero similique iusto? Sunt dolorum alias totam delectus dolor doloribus soluta molestiae provident fuga quo. Ab id totam vel nisi voluptas. Suscipit cum vitae eligendi exercitationem impedit, nam commodi placeat adipisci inventore nisi nihil dolorem soluta modi corporis voluptas architecto numquam itaque nostrum doloribus', 

'ipsum facilis non nulla? A fugiat fugit consequuntur vero dignissimos consequatur aut soluta. Ad autem dicta consectetur veritatis vero consequatur perferendis molestias in vitae voluptate, molestiae commodi quod et ratione tempore tenetur nam ipsam sunt adipisci eligendi ab similique quae repellat? Odit aliquam temporibus ea amet necessitatibus atque magnam nostrum modi tenetur, porro fugiat illum ipsum accusantium odio ut. Nostrum unde quidem commodi! Maxime, distinctio. Perferendis laboriosam molestias reiciendis quo sequi aperiam qui quos distinctio ut voluptates sint in consectetur at, ab, alias dignissimos excepturi impedit reprehenderit asperiores natus provident! Libero, dolorem reiciendis ab nisi praesentium voluptates voluptas provident necessitatibus rem',

'molestias possimus accusamus eligendi ipsam delectus fugit esse in vel dolor consectetur. Iste enim esse temporibus reprehenderit? Quis illo, ullam dolorum recusandae quos minima fugit doloremque reiciendis quo! Repudiandae explicabo dolores omnis corrupti voluptas quis quam maiores commodi porro, voluptate recusandae voluptatem a? Quis maiores molestiae consectetur accusantium perspiciatis corrupti amet recusandae quasi earum non. Itaque necessitatibus tempore velit adipisci molestiae, cupiditate qui minima sint mollitia repudiandae. Obcaecati dolor asperiores labore mollitia eius facilis sed! Et porro quo, est aspernatur, ut nobis dolorem facilis doloremque amet dolores molestiae rem aliquam possimus delectus quidem laudantium voluptatem eius itaque optio odit dolorum aliquid tempore placeat. Libero incidunt esse doloribus asperiores eos vel quidem saepe ex voluptatibus eveniet velit aspernatur odio dolorem necessitatibus repudiandae in',

'placeat doloremque veniam officia quia optio consequatur quasi nesciunt. Magnam numquam dolorem quisquam obcaecati fuga voluptatibus praesentium fugit nam temporibus mollitia! Fugiat aut, unde repudiandae odio aspernatur itaque ullam quidem reprehenderit illum, quod qui sit nisi! Velit accusamus, exercitationem ducimus in modi tempore tempora reprehenderit obcaecati quibusdam. Dolores adipisci, ipsum quo maxime debitis eius libero dolor quaerat nostrum quibusdam incidunt, quas harum unde maiores tenetur praesentium aliquid error similique perferendis illo! Ex dolorum illo hic nobis asperiores eum non temporibus!',

'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor soluta minus quaerat ex voluptatem quidem dignissimos corporis delectus enim nemo nam architecto velit doloribus molestiae autem, rem optio libero excepturi unde commodi eaque nisi dolorum! Deserunt quia accusantium ipsa, labore nisi rem dolorum inventore illum aut deleniti quis ab voluptatum sit cupiditate modi. Nemo laboriosam maxime libero similique iusto? Sunt dolorum alias totam delectus dolor doloribus soluta molestiae provident fuga quo. Ab id totam vel nisi voluptas. Suscipit cum vitae eligendi exercitationem impedit, nam commodi placeat adipisci inventore nisi nihil dolorem soluta modi corporis voluptas architecto numquam itaque nostrum doloribus', 

'ipsum facilis non nulla? A fugiat fugit consequuntur vero dignissimos consequatur aut soluta. Ad autem dicta consectetur veritatis vero consequatur perferendis molestias in vitae voluptate, molestiae commodi quod et ratione tempore tenetur nam ipsam sunt adipisci eligendi ab similique quae repellat? Odit aliquam temporibus ea amet necessitatibus atque magnam nostrum modi tenetur, porro fugiat illum ipsum accusantium odio ut. Nostrum unde quidem commodi! Maxime, distinctio. Perferendis laboriosam molestias reiciendis quo sequi aperiam qui quos distinctio ut voluptates sint in consectetur at, ab, alias dignissimos excepturi impedit reprehenderit asperiores natus provident! Libero, dolorem reiciendis ab nisi praesentium voluptates voluptas provident necessitatibus rem',

'molestias possimus accusamus eligendi ipsam delectus fugit esse in vel dolor consectetur. Iste enim esse temporibus reprehenderit? Quis illo, ullam dolorum recusandae quos minima fugit doloremque reiciendis quo! Repudiandae explicabo dolores omnis corrupti voluptas quis quam maiores commodi porro, voluptate recusandae voluptatem a? Quis maiores molestiae consectetur accusantium perspiciatis corrupti amet recusandae quasi earum non. Itaque necessitatibus tempore velit adipisci molestiae, cupiditate qui minima sint mollitia repudiandae. Obcaecati dolor asperiores labore mollitia eius facilis sed! Et porro quo, est aspernatur, ut nobis dolorem facilis doloremque amet dolores molestiae rem aliquam possimus delectus quidem laudantium voluptatem eius itaque optio odit dolorum aliquid tempore placeat. Libero incidunt esse doloribus asperiores eos vel quidem saepe ex voluptatibus eveniet velit aspernatur odio dolorem necessitatibus repudiandae in',

'placeat doloremque veniam officia quia optio consequatur quasi nesciunt. Magnam numquam dolorem quisquam obcaecati fuga voluptatibus praesentium fugit nam temporibus mollitia! Fugiat aut, unde repudiandae odio aspernatur itaque ullam quidem reprehenderit illum, quod qui sit nisi! Velit accusamus, exercitationem ducimus in modi tempore tempora reprehenderit obcaecati quibusdam. Dolores adipisci, ipsum quo maxime debitis eius libero dolor quaerat nostrum quibusdam incidunt, quas harum unde maiores tenetur praesentium aliquid error similique perferendis illo! Ex dolorum illo hic nobis asperiores eum non temporibus!',

'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor soluta minus quaerat ex voluptatem quidem dignissimos corporis delectus enim nemo nam architecto velit doloribus molestiae autem, rem optio libero excepturi unde commodi eaque nisi dolorum! Deserunt quia accusantium ipsa, labore nisi rem dolorum inventore illum aut deleniti quis ab voluptatum sit cupiditate modi. Nemo laboriosam maxime libero similique iusto? Sunt dolorum alias totam delectus dolor doloribus soluta molestiae provident fuga quo. Ab id totam vel nisi voluptas. Suscipit cum vitae eligendi exercitationem impedit, nam commodi placeat adipisci inventore nisi nihil dolorem soluta modi corporis voluptas architecto numquam itaque nostrum doloribus', 

'ipsum facilis non nulla? A fugiat fugit consequuntur vero dignissimos consequatur aut soluta. Ad autem dicta consectetur veritatis vero consequatur perferendis molestias in vitae voluptate, molestiae commodi quod et ratione tempore tenetur nam ipsam sunt adipisci eligendi ab similique quae repellat? Odit aliquam temporibus ea amet necessitatibus atque magnam nostrum modi tenetur, porro fugiat illum ipsum accusantium odio ut. Nostrum unde quidem commodi! Maxime, distinctio. Perferendis laboriosam molestias reiciendis quo sequi aperiam qui quos distinctio ut voluptates sint in consectetur at, ab, alias dignissimos excepturi impedit reprehenderit asperiores natus provident! Libero, dolorem reiciendis ab nisi praesentium voluptates voluptas provident necessitatibus rem',

'molestias possimus accusamus eligendi ipsam delectus fugit esse in vel dolor consectetur. Iste enim esse temporibus reprehenderit? Quis illo, ullam dolorum recusandae quos minima fugit doloremque reiciendis quo! Repudiandae explicabo dolores omnis corrupti voluptas quis quam maiores commodi porro, voluptate recusandae voluptatem a? Quis maiores molestiae consectetur accusantium perspiciatis corrupti amet recusandae quasi earum non. Itaque necessitatibus tempore velit adipisci molestiae, cupiditate qui minima sint mollitia repudiandae. Obcaecati dolor asperiores labore mollitia eius facilis sed! Et porro quo, est aspernatur, ut nobis dolorem facilis doloremque amet dolores molestiae rem aliquam possimus delectus quidem laudantium voluptatem eius itaque optio odit dolorum aliquid tempore placeat. Libero incidunt esse doloribus asperiores eos vel quidem saepe ex voluptatibus eveniet velit aspernatur odio dolorem necessitatibus repudiandae in',

'placeat doloremque veniam officia quia optio consequatur quasi nesciunt. Magnam numquam dolorem quisquam obcaecati fuga voluptatibus praesentium fugit nam temporibus mollitia! Fugiat aut, unde repudiandae odio aspernatur itaque ullam quidem reprehenderit illum, quod qui sit nisi! Velit accusamus, exercitationem ducimus in modi tempore tempora reprehenderit obcaecati quibusdam. Dolores adipisci, ipsum quo maxime debitis eius libero dolor quaerat nostrum quibusdam incidunt, quas harum unde maiores tenetur praesentium aliquid error similique perferendis illo! Ex dolorum illo hic nobis asperiores eum non temporibus!',];

const item = document.querySelector("#items")
const dataContainer = document.querySelector("#data")
const generate = () => {
    if (isNaN(item.value)||item.value < 0 || item.value > 12) {
        const randomIndex = Math.floor(Math.random() * text.length) 
        dataContainer.innerHTML = `<p> ${text[randomIndex]} <p/>`
    } else {
       
    }
}